apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: marmak
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git # This is a placeholder, usually it would be THIS repo
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: marmak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
